---
- name: set mongodb_version
  set_fact:
    mongodb_version: "{{ mongodb_minor_release | regex_search('^([0-9]+.[0-9]+).[0-9]+$', '\\1') }}"

- name: install apt-utils
  apt:
    pkg:
      - apt-utils
  become: yes

- name: add mongodb key file
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    state: present
  become: yes

- name: add mongodb repository
  apt_repository:
    repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    filename: mongodb-org-{{ mongodb_version }}
    update_cache: yes
  become: yes

- name: install mongodb {{ mongodb_minor_release }} packages
  apt:
    pkg:
      - apt-utils
      - mongodb-org={{ mongodb_minor_release }}
      - mongodb-org-server={{ mongodb_minor_release }}
      - mongodb-org-shell={{ mongodb_minor_release }}
      - mongodb-org-mongos={{ mongodb_minor_release }}
      - mongodb-org-tools={{ mongodb_minor_release }}
  become: yes

- name: hold mongodb packages in the version installed
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools
  become: yes

- name: setup mongod configuration
  template:
    src: '{{ mongodb_configuration_template_file_path }}'
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode:  '0644'
  become: yes

- name: adjusts tcp keepalive time, according to https://docs.mongodb.com/manual/faq/diagnostics/#adjusting-the-tcp-keepalive-value
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: '{{ mongodb_tcp_keep_alive_time }}'
  when: mongodb_tcp_keep_alive_time|length > 0
  become: yes

- name: ensure path /data/db exists
  file:
    path: /data/db
    state: directory
  become: yes

- name: ensure mongodb has started up
  service:
    name: mongod
    state: started
    enabled: yes
  tags:
    - notest
  become: yes
