---
- name: add mongodb key file
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  become: yes

- name: add mongodb repository
  apt_repository:
    repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse"
    state: present
    filename: mongodb-org-4.2
    update_cache: yes
  become: yes

- name: install mongodb 4.2.7 packages
  apt:
    pkg:
      - mongodb-org=4.2.7
      - mongodb-org-server=4.2.7
      - mongodb-org-shell=4.2.7
      - mongodb-org-mongos=4.2.7
      - mongodb-org-tools=4.2.7
  become: yes

- name: hold mongodb packages in the version installed
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools
  become: yes

- name: setup mongod configuration
  template:
    src: '{{ mongodb_configuration_template_file_path }}'
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode:  '0644'
  become: yes

- name: adjusts tcp keepalive time, according to https://docs.mongodb.com/manual/faq/diagnostics/#adjusting-the-tcp-keepalive-value
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: '{{ mongodb_tcp_keep_alive_time }}'
  when: mongodb_tcp_keep_alive_time is defined
  become: yes

- name: ensure path /data/db exists
  file:
    path: /data/db
    state: directory
  become: yes

- name: ensure mongodb has started up
  service:
    name: mongod
    state: started
    enabled: yes
  tags:
    - notest
  become: yes
